#############################################################################
# Makefile for building: wfview
# Generated by qmake (3.1) (Qt 5.15.3)
# Project:  wfview.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile wfview.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DUSB_CONTROLLER -DWFVIEW_VERSION=\"1.65\" -DBUILD_WFVIEW -D__LINUX_PULSE__ -DQT_DEPRECATED_WARNINGS -DQCUSTOMPLOT_USE_LIBRARY -DUSE_SSE -DUSE_SSE2 -DOUTSIDE_SPEEX -DRANDOM_PREFIX=wf -DEIGEN_MPL2_ONLY -DEIGEN_DONT_VECTORIZE -DEIGEN_VECTORIZE_SSE3 -DPREFIX=\"/usr/local\" -DHOST=\"`hostname`\" -DUNAME=\"`whoami`\" -DGITSHORT=\"$(shell git -C "/home/bob/work/wfview--20240227--12-24-00/wfview" rev-parse --short HEAD)\" -DQT_NO_DEBUG -DQT_MULTIMEDIA_LIB -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GAMEPAD_LIB -DQT_GUI_LIB -DQT_SERIALPORT_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -s -fvisibility=hidden -fvisibility-inlines-hidden -faligned-new -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -Iresampler -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGamepad -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = wfview1.0.0
DISTDIR = /home/bob/work/wfview--20240227--12-24-00/wfview/.tmp/wfview1.0.0
LINK          = g++
LFLAGS        = -O2 -s -Wl,-O1
LIBS          = $(SUBLIBS) -lpulse -lpulse-simple -lrtaudio -ludev -lportaudio -lqcustomplot -L./ -lhidapi-libusb -lopus /usr/lib/x86_64-linux-gnu/libQt5Multimedia.so /usr/lib/x86_64-linux-gnu/libQt5PrintSupport.so /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gamepad.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5SerialPort.so /usr/lib/x86_64-linux-gnu/libQt5Network.so /usr/lib/x86_64-linux-gnu/libQt5Xml.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		cwsender.cpp \
		cwsidetone.cpp \
		loggingwindow.cpp \
		wfmain.cpp \
		commhandler.cpp \
		rigcommander.cpp \
		freqmemory.cpp \
		rigidentities.cpp \
		udpbase.cpp \
		udphandler.cpp \
		udpcivdata.cpp \
		udpaudio.cpp \
		logcategories.cpp \
		pahandler.cpp \
		rthandler.cpp \
		audiohandler.cpp \
		audioconverter.cpp \
		calibrationwindow.cpp \
		satellitesetup.cpp \
		udpserver.cpp \
		meter.cpp \
		qledlabel.cpp \
		pttyhandler.cpp \
		resampler/resample.c \
		repeatersetup.cpp \
		rigctld.cpp \
		usbcontroller.cpp \
		controllersetup.cpp \
		transceiveradjustments.cpp \
		selectradio.cpp \
		tcpserver.cpp \
		cluster.cpp \
		database.cpp \
		aboutbox.cpp \
		audiodevices.cpp qrc_style.cpp \
		qrc_resources.cpp \
		moc_wfmain.cpp \
		moc_commhandler.cpp \
		moc_cwsender.cpp \
		moc_cwsidetone.cpp \
		moc_loggingwindow.cpp \
		moc_rigcommander.cpp \
		moc_udphandler.cpp \
		moc_udpcivdata.cpp \
		moc_udpaudio.cpp \
		moc_pahandler.cpp \
		moc_rthandler.cpp \
		moc_audiohandler.cpp \
		moc_audioconverter.cpp \
		moc_calibrationwindow.cpp \
		moc_satellitesetup.cpp \
		moc_udpserver.cpp \
		moc_meter.cpp \
		moc_qledlabel.cpp \
		moc_pttyhandler.cpp \
		moc_repeatersetup.cpp \
		moc_rigctld.cpp \
		moc_usbcontroller.cpp \
		moc_controllersetup.cpp \
		moc_transceiveradjustments.cpp \
		moc_selectradio.cpp \
		moc_tcpserver.cpp \
		moc_cluster.cpp \
		moc_aboutbox.cpp \
		moc_audiodevices.cpp
OBJECTS       = main.o \
		cwsender.o \
		cwsidetone.o \
		loggingwindow.o \
		wfmain.o \
		commhandler.o \
		rigcommander.o \
		freqmemory.o \
		rigidentities.o \
		udpbase.o \
		udphandler.o \
		udpcivdata.o \
		udpaudio.o \
		logcategories.o \
		pahandler.o \
		rthandler.o \
		audiohandler.o \
		audioconverter.o \
		calibrationwindow.o \
		satellitesetup.o \
		udpserver.o \
		meter.o \
		qledlabel.o \
		pttyhandler.o \
		resample.o \
		repeatersetup.o \
		rigctld.o \
		usbcontroller.o \
		controllersetup.o \
		transceiveradjustments.o \
		selectradio.o \
		tcpserver.o \
		cluster.o \
		database.o \
		aboutbox.o \
		audiodevices.o \
		qrc_style.o \
		qrc_resources.o \
		moc_wfmain.o \
		moc_commhandler.o \
		moc_cwsender.o \
		moc_cwsidetone.o \
		moc_loggingwindow.o \
		moc_rigcommander.o \
		moc_udphandler.o \
		moc_udpcivdata.o \
		moc_udpaudio.o \
		moc_pahandler.o \
		moc_rthandler.o \
		moc_audiohandler.o \
		moc_audioconverter.o \
		moc_calibrationwindow.o \
		moc_satellitesetup.o \
		moc_udpserver.o \
		moc_meter.o \
		moc_qledlabel.o \
		moc_pttyhandler.o \
		moc_repeatersetup.o \
		moc_rigctld.o \
		moc_usbcontroller.o \
		moc_controllersetup.o \
		moc_transceiveradjustments.o \
		moc_selectradio.o \
		moc_tcpserver.o \
		moc_cluster.o \
		moc_aboutbox.o \
		moc_audiodevices.o
DIST          = resources/unix_icons/wfview.png \
		resources/install.sh \
		resources/wfview.desktop \
		resources/org.wfview.wfview.metainfo.xml \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		wfview.pro wfmain.h \
		colorprefs.h \
		commhandler.h \
		cwsender.h \
		cwsidetone.h \
		loggingwindow.h \
		prefs.h \
		printhex.h \
		rigcommander.h \
		freqmemory.h \
		rigidentities.h \
		sidebandchooser.h \
		udpbase.h \
		udphandler.h \
		udpcivdata.h \
		udpaudio.h \
		logcategories.h \
		pahandler.h \
		rthandler.h \
		audiohandler.h \
		audioconverter.h \
		calibrationwindow.h \
		satellitesetup.h \
		udpserver.h \
		packettypes.h \
		meter.h \
		qledlabel.h \
		pttyhandler.h \
		resampler/speex_resampler.h \
		resampler/arch.h \
		resampler/resample_sse.h \
		repeatersetup.h \
		repeaterattributes.h \
		rigctld.h \
		rigstate.h \
		ulaw.h \
		usbcontroller.h \
		controllersetup.h \
		transceiveradjustments.h \
		audiotaper.h \
		selectradio.h \
		tcpserver.h \
		cluster.h \
		database.h \
		aboutbox.h \
		wfviewtypes.h \
		audiodevices.h main.cpp \
		cwsender.cpp \
		cwsidetone.cpp \
		loggingwindow.cpp \
		wfmain.cpp \
		commhandler.cpp \
		rigcommander.cpp \
		freqmemory.cpp \
		rigidentities.cpp \
		udpbase.cpp \
		udphandler.cpp \
		udpcivdata.cpp \
		udpaudio.cpp \
		logcategories.cpp \
		pahandler.cpp \
		rthandler.cpp \
		audiohandler.cpp \
		audioconverter.cpp \
		calibrationwindow.cpp \
		satellitesetup.cpp \
		udpserver.cpp \
		meter.cpp \
		qledlabel.cpp \
		pttyhandler.cpp \
		resampler/resample.c \
		repeatersetup.cpp \
		rigctld.cpp \
		usbcontroller.cpp \
		controllersetup.cpp \
		transceiveradjustments.cpp \
		selectradio.cpp \
		tcpserver.cpp \
		cluster.cpp \
		database.cpp \
		aboutbox.cpp \
		audiodevices.cpp
QMAKE_TARGET  = wfview
DESTDIR       = 
TARGET        = wfview


first: all
####### Build rules

wfview: ui_wfmain.h ui_calibrationwindow.h ui_cwsender.h ui_loggingwindow.h ui_satellitesetup.h ui_selectradio.h ui_repeatersetup.h ui_transceiveradjustments.h ui_controllersetup.h ui_aboutbox.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: wfview.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		wfview.pro \
		qdarkstyle/style.qrc \
		resources/resources.qrc
	$(QMAKE) -o Makefile wfview.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gamepad.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_websockets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
wfview.pro:
qdarkstyle/style.qrc:
resources/resources.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile wfview.pro

qmake_all: FORCE


all: Makefile wfview

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents qdarkstyle/style.qrc resources/resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents wfmain.h colorprefs.h commhandler.h cwsender.h cwsidetone.h loggingwindow.h prefs.h printhex.h rigcommander.h freqmemory.h rigidentities.h sidebandchooser.h udpbase.h udphandler.h udpcivdata.h udpaudio.h logcategories.h pahandler.h rthandler.h audiohandler.h audioconverter.h calibrationwindow.h satellitesetup.h udpserver.h packettypes.h meter.h qledlabel.h pttyhandler.h resampler/speex_resampler.h resampler/arch.h resampler/resample_sse.h repeatersetup.h repeaterattributes.h rigctld.h rigstate.h ulaw.h usbcontroller.h controllersetup.h transceiveradjustments.h audiotaper.h selectradio.h tcpserver.h cluster.h database.h aboutbox.h wfviewtypes.h audiodevices.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp cwsender.cpp cwsidetone.cpp loggingwindow.cpp wfmain.cpp commhandler.cpp rigcommander.cpp freqmemory.cpp rigidentities.cpp udpbase.cpp udphandler.cpp udpcivdata.cpp udpaudio.cpp logcategories.cpp pahandler.cpp rthandler.cpp audiohandler.cpp audioconverter.cpp calibrationwindow.cpp satellitesetup.cpp udpserver.cpp meter.cpp qledlabel.cpp pttyhandler.cpp resampler/resample.c repeatersetup.cpp rigctld.cpp usbcontroller.cpp controllersetup.cpp transceiveradjustments.cpp selectradio.cpp tcpserver.cpp cluster.cpp database.cpp aboutbox.cpp audiodevices.cpp $(DISTDIR)/
	$(COPY_FILE) --parents wfmain.ui calibrationwindow.ui cwsender.ui loggingwindow.ui satellitesetup.ui selectradio.ui repeatersetup.ui transceiveradjustments.ui controllersetup.ui aboutbox.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_style.cpp qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_style.cpp qrc_resources.cpp
qrc_style.cpp: qdarkstyle/style.qrc \
		/usr/lib/qt5/bin/rcc \
		qdarkstyle/rc/Vsepartoolbar.png \
		qdarkstyle/rc/close-pressed.png \
		qdarkstyle/rc/Hmovetoolbar.png \
		qdarkstyle/rc/up_arrow.png \
		qdarkstyle/rc/left_arrow_disabled.png \
		qdarkstyle/rc/close-hover.png \
		qdarkstyle/rc/checkbox_unchecked.png \
		qdarkstyle/rc/radio_unchecked_disabled.png \
		qdarkstyle/rc/radio_checked.png \
		qdarkstyle/rc/checkbox_checked_disabled.png \
		qdarkstyle/rc/Hsepartoolbar.png \
		qdarkstyle/rc/sizegrip.png \
		qdarkstyle/rc/down_arrow.png \
		qdarkstyle/rc/stylesheet-branch-more.png \
		qdarkstyle/rc/radio_unchecked.png \
		qdarkstyle/rc/branch_closed-on.png \
		qdarkstyle/rc/checkbox_unchecked_disabled.png \
		qdarkstyle/rc/branch_open.png \
		qdarkstyle/rc/left_arrow.png \
		qdarkstyle/rc/stylesheet-branch-end.png \
		qdarkstyle/rc/undock.png \
		qdarkstyle/rc/right_arrow.png \
		qdarkstyle/rc/checkbox_indeterminate.png \
		qdarkstyle/rc/checkbox_checked_focus.png \
		qdarkstyle/rc/stylesheet-vline.png \
		qdarkstyle/rc/radio_checked_focus.png \
		qdarkstyle/rc/branch_closed.png \
		qdarkstyle/rc/right_arrow_disabled.png \
		qdarkstyle/rc/down_arrow_disabled.png \
		qdarkstyle/rc/branch_open-on.png \
		qdarkstyle/rc/radio_unchecked_focus.png \
		qdarkstyle/rc/Vmovetoolbar.png \
		qdarkstyle/rc/transparent.png \
		qdarkstyle/rc/close.png \
		qdarkstyle/rc/radio_checked_disabled.png \
		qdarkstyle/rc/checkbox_checked.png \
		qdarkstyle/rc/up_arrow_disabled.png \
		qdarkstyle/rc/checkbox_indeterminate_focus.png \
		qdarkstyle/rc/checkbox_unchecked_focus.png \
		qdarkstyle/style.qss
	/usr/lib/qt5/bin/rcc -name style qdarkstyle/style.qrc -o qrc_style.cpp

qrc_resources.cpp: resources/resources.qrc \
		/usr/lib/qt5/bin/rcc \
		resources/quickkeys.png \
		resources/shuttlepro.png \
		resources/streamdeckmini.png \
		resources/streamdeck.png \
		resources/streamdeckplus.png \
		resources/rc28.png \
		resources/xbox.png \
		resources/wfview.png \
		resources/streamdeckpedal.png \
		resources/shuttlexpress.png \
		resources/ecoder.png \
		resources/streamdeckxl.png
	/usr/lib/qt5/bin/rcc -name resources resources/resources.qrc -o qrc_resources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -s -fvisibility=hidden -fvisibility-inlines-hidden -faligned-new -O2 -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_wfmain.cpp moc_commhandler.cpp moc_cwsender.cpp moc_cwsidetone.cpp moc_loggingwindow.cpp moc_rigcommander.cpp moc_udphandler.cpp moc_udpcivdata.cpp moc_udpaudio.cpp moc_pahandler.cpp moc_rthandler.cpp moc_audiohandler.cpp moc_audioconverter.cpp moc_calibrationwindow.cpp moc_satellitesetup.cpp moc_udpserver.cpp moc_meter.cpp moc_qledlabel.cpp moc_pttyhandler.cpp moc_repeatersetup.cpp moc_rigctld.cpp moc_usbcontroller.cpp moc_controllersetup.cpp moc_transceiveradjustments.cpp moc_selectradio.cpp moc_tcpserver.cpp moc_cluster.cpp moc_aboutbox.cpp moc_audiodevices.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_wfmain.cpp moc_commhandler.cpp moc_cwsender.cpp moc_cwsidetone.cpp moc_loggingwindow.cpp moc_rigcommander.cpp moc_udphandler.cpp moc_udpcivdata.cpp moc_udpaudio.cpp moc_pahandler.cpp moc_rthandler.cpp moc_audiohandler.cpp moc_audioconverter.cpp moc_calibrationwindow.cpp moc_satellitesetup.cpp moc_udpserver.cpp moc_meter.cpp moc_qledlabel.cpp moc_pttyhandler.cpp moc_repeatersetup.cpp moc_rigctld.cpp moc_usbcontroller.cpp moc_controllersetup.cpp moc_transceiveradjustments.cpp moc_selectradio.cpp moc_tcpserver.cpp moc_cluster.cpp moc_aboutbox.cpp moc_audiodevices.cpp
moc_wfmain.cpp: wfmain.h \
		servermain.h \
		logcategories.h \
		commhandler.h \
		wfviewtypes.h \
		rigcommander.h \
		pttyhandler.h \
		rigidentities.h \
		freqmemory.h \
		packettypes.h \
		udphandler.h \
		audiohandler.h \
		audiotaper.h \
		audioconverter.h \
		resampler/speex_resampler.h \
		udpbase.h \
		udpcivdata.h \
		udpaudio.h \
		pahandler.h \
		rthandler.h \
		repeaterattributes.h \
		tcpserver.h \
		rigstate.h \
		audiodevices.h \
		udpserver.h \
		rigctld.h \
		prefs.h \
		calibrationwindow.h \
		repeatersetup.h \
		satellitesetup.h \
		transceiveradjustments.h \
		cwsender.h \
		cwsidetone.h \
		qledlabel.h \
		aboutbox.h \
		selectradio.h \
		colorprefs.h \
		loggingwindow.h \
		cluster.h \
		database.h \
		sidebandchooser.h \
		usbcontroller.h \
		controllersetup.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/bob/work/wfview--20240227--12-24-00/wfview/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/bob/work/wfview--20240227--12-24-00/wfview -I/home/bob/work/wfview--20240227--12-24-00/wfview/resampler -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGamepad -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include wfmain.h -o moc_wfmain.cpp

moc_commhandler.cpp: commhandler.h \
		wfviewtypes.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/bob/work/wfview--20240227--12-24-00/wfview/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/bob/work/wfview--20240227--12-24-00/wfview -I/home/bob/work/wfview--20240227--12-24-00/wfview/resampler -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGamepad -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include commhandler.h -o moc_commhandler.cpp

moc_cwsender.cpp: cwsender.h \
		cwsidetone.h \
		wfviewtypes.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/bob/work/wfview--20240227--12-24-00/wfview/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/bob/work/wfview--20240227--12-24-00/wfview -I/home/bob/work/wfview--20240227--12-24-00/wfview/resampler -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGamepad -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include cwsender.h -o moc_cwsender.cpp

moc_cwsidetone.cpp: cwsidetone.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/bob/work/wfview--20240227--12-24-00/wfview/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/bob/work/wfview--20240227--12-24-00/wfview -I/home/bob/work/wfview--20240227--12-24-00/wfview/resampler -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGamepad -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include cwsidetone.h -o moc_cwsidetone.cpp

moc_loggingwindow.cpp: loggingwindow.h \
		logcategories.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/bob/work/wfview--20240227--12-24-00/wfview/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/bob/work/wfview--20240227--12-24-00/wfview -I/home/bob/work/wfview--20240227--12-24-00/wfview/resampler -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGamepad -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include loggingwindow.h -o moc_loggingwindow.cpp

moc_rigcommander.cpp: rigcommander.h \
		wfviewtypes.h \
		commhandler.h \
		pttyhandler.h \
		rigidentities.h \
		freqmemory.h \
		packettypes.h \
		udphandler.h \
		audiohandler.h \
		audiotaper.h \
		audioconverter.h \
		resampler/speex_resampler.h \
		udpbase.h \
		udpcivdata.h \
		udpaudio.h \
		pahandler.h \
		rthandler.h \
		repeaterattributes.h \
		tcpserver.h \
		rigstate.h \
		rigcommander.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/bob/work/wfview--20240227--12-24-00/wfview/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/bob/work/wfview--20240227--12-24-00/wfview -I/home/bob/work/wfview--20240227--12-24-00/wfview/resampler -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGamepad -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include rigcommander.h -o moc_rigcommander.cpp

moc_udphandler.cpp: udphandler.h \
		packettypes.h \
		audiohandler.h \
		audiotaper.h \
		audioconverter.h \
		wfviewtypes.h \
		resampler/speex_resampler.h \
		udpbase.h \
		udpcivdata.h \
		udpaudio.h \
		pahandler.h \
		rthandler.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/bob/work/wfview--20240227--12-24-00/wfview/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/bob/work/wfview--20240227--12-24-00/wfview -I/home/bob/work/wfview--20240227--12-24-00/wfview/resampler -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGamepad -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include udphandler.h -o moc_udphandler.cpp

moc_udpcivdata.cpp: udpcivdata.h \
		packettypes.h \
		udpbase.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/bob/work/wfview--20240227--12-24-00/wfview/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/bob/work/wfview--20240227--12-24-00/wfview -I/home/bob/work/wfview--20240227--12-24-00/wfview/resampler -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGamepad -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include udpcivdata.h -o moc_udpcivdata.cpp

moc_udpaudio.cpp: udpaudio.h \
		packettypes.h \
		udpbase.h \
		audiohandler.h \
		audiotaper.h \
		audioconverter.h \
		wfviewtypes.h \
		resampler/speex_resampler.h \
		pahandler.h \
		rthandler.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/bob/work/wfview--20240227--12-24-00/wfview/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/bob/work/wfview--20240227--12-24-00/wfview -I/home/bob/work/wfview--20240227--12-24-00/wfview/resampler -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGamepad -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include udpaudio.h -o moc_udpaudio.cpp

moc_pahandler.cpp: pahandler.h \
		packettypes.h \
		audiotaper.h \
		audiohandler.h \
		audioconverter.h \
		wfviewtypes.h \
		resampler/speex_resampler.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/bob/work/wfview--20240227--12-24-00/wfview/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/bob/work/wfview--20240227--12-24-00/wfview -I/home/bob/work/wfview--20240227--12-24-00/wfview/resampler -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGamepad -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include pahandler.h -o moc_pahandler.cpp

moc_rthandler.cpp: rthandler.h \
		packettypes.h \
		audiotaper.h \
		audiohandler.h \
		audioconverter.h \
		wfviewtypes.h \
		resampler/speex_resampler.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/bob/work/wfview--20240227--12-24-00/wfview/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/bob/work/wfview--20240227--12-24-00/wfview -I/home/bob/work/wfview--20240227--12-24-00/wfview/resampler -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGamepad -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include rthandler.h -o moc_rthandler.cpp

moc_audiohandler.cpp: audiohandler.h \
		packettypes.h \
		audiotaper.h \
		audioconverter.h \
		wfviewtypes.h \
		resampler/speex_resampler.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/bob/work/wfview--20240227--12-24-00/wfview/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/bob/work/wfview--20240227--12-24-00/wfview -I/home/bob/work/wfview--20240227--12-24-00/wfview/resampler -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGamepad -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include audiohandler.h -o moc_audiohandler.cpp

moc_audioconverter.cpp: audioconverter.h \
		wfviewtypes.h \
		resampler/speex_resampler.h \
		packettypes.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/bob/work/wfview--20240227--12-24-00/wfview/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/bob/work/wfview--20240227--12-24-00/wfview -I/home/bob/work/wfview--20240227--12-24-00/wfview/resampler -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGamepad -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include audioconverter.h -o moc_audioconverter.cpp

moc_calibrationwindow.cpp: calibrationwindow.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/bob/work/wfview--20240227--12-24-00/wfview/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/bob/work/wfview--20240227--12-24-00/wfview -I/home/bob/work/wfview--20240227--12-24-00/wfview/resampler -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGamepad -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include calibrationwindow.h -o moc_calibrationwindow.cpp

moc_satellitesetup.cpp: satellitesetup.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/bob/work/wfview--20240227--12-24-00/wfview/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/bob/work/wfview--20240227--12-24-00/wfview -I/home/bob/work/wfview--20240227--12-24-00/wfview/resampler -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGamepad -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include satellitesetup.h -o moc_satellitesetup.cpp

moc_udpserver.cpp: udpserver.h \
		packettypes.h \
		rigidentities.h \
		freqmemory.h \
		wfviewtypes.h \
		udphandler.h \
		audiohandler.h \
		audiotaper.h \
		audioconverter.h \
		resampler/speex_resampler.h \
		udpbase.h \
		udpcivdata.h \
		udpaudio.h \
		pahandler.h \
		rthandler.h \
		rigcommander.h \
		commhandler.h \
		pttyhandler.h \
		repeaterattributes.h \
		tcpserver.h \
		rigstate.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/bob/work/wfview--20240227--12-24-00/wfview/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/bob/work/wfview--20240227--12-24-00/wfview -I/home/bob/work/wfview--20240227--12-24-00/wfview/resampler -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGamepad -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include udpserver.h -o moc_udpserver.cpp

moc_meter.cpp: meter.h \
		rigcommander.h \
		wfviewtypes.h \
		commhandler.h \
		pttyhandler.h \
		rigidentities.h \
		freqmemory.h \
		packettypes.h \
		udphandler.h \
		audiohandler.h \
		audiotaper.h \
		audioconverter.h \
		resampler/speex_resampler.h \
		udpbase.h \
		udpcivdata.h \
		udpaudio.h \
		pahandler.h \
		rthandler.h \
		repeaterattributes.h \
		tcpserver.h \
		rigstate.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/bob/work/wfview--20240227--12-24-00/wfview/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/bob/work/wfview--20240227--12-24-00/wfview -I/home/bob/work/wfview--20240227--12-24-00/wfview/resampler -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGamepad -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include meter.h -o moc_meter.cpp

moc_qledlabel.cpp: qledlabel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/bob/work/wfview--20240227--12-24-00/wfview/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/bob/work/wfview--20240227--12-24-00/wfview -I/home/bob/work/wfview--20240227--12-24-00/wfview/resampler -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGamepad -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include qledlabel.h -o moc_qledlabel.cpp

moc_pttyhandler.cpp: pttyhandler.h \
		rigidentities.h \
		freqmemory.h \
		wfviewtypes.h \
		packettypes.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/bob/work/wfview--20240227--12-24-00/wfview/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/bob/work/wfview--20240227--12-24-00/wfview -I/home/bob/work/wfview--20240227--12-24-00/wfview/resampler -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGamepad -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include pttyhandler.h -o moc_pttyhandler.cpp

moc_repeatersetup.cpp: repeatersetup.h \
		repeaterattributes.h \
		rigidentities.h \
		freqmemory.h \
		wfviewtypes.h \
		packettypes.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/bob/work/wfview--20240227--12-24-00/wfview/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/bob/work/wfview--20240227--12-24-00/wfview -I/home/bob/work/wfview--20240227--12-24-00/wfview/resampler -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGamepad -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include repeatersetup.h -o moc_repeatersetup.cpp

moc_rigctld.cpp: rigctld.h \
		rigcommander.h \
		wfviewtypes.h \
		commhandler.h \
		pttyhandler.h \
		rigidentities.h \
		freqmemory.h \
		packettypes.h \
		udphandler.h \
		audiohandler.h \
		audiotaper.h \
		audioconverter.h \
		resampler/speex_resampler.h \
		udpbase.h \
		udpcivdata.h \
		udpaudio.h \
		pahandler.h \
		rthandler.h \
		repeaterattributes.h \
		tcpserver.h \
		rigstate.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/bob/work/wfview--20240227--12-24-00/wfview/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/bob/work/wfview--20240227--12-24-00/wfview -I/home/bob/work/wfview--20240227--12-24-00/wfview/resampler -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGamepad -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include rigctld.h -o moc_rigctld.cpp

moc_usbcontroller.cpp: usbcontroller.h \
		rigidentities.h \
		freqmemory.h \
		wfviewtypes.h \
		packettypes.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/bob/work/wfview--20240227--12-24-00/wfview/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/bob/work/wfview--20240227--12-24-00/wfview -I/home/bob/work/wfview--20240227--12-24-00/wfview/resampler -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGamepad -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include usbcontroller.h -o moc_usbcontroller.cpp

moc_controllersetup.cpp: controllersetup.h \
		usbcontroller.h \
		rigidentities.h \
		freqmemory.h \
		wfviewtypes.h \
		packettypes.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/bob/work/wfview--20240227--12-24-00/wfview/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/bob/work/wfview--20240227--12-24-00/wfview -I/home/bob/work/wfview--20240227--12-24-00/wfview/resampler -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGamepad -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include controllersetup.h -o moc_controllersetup.cpp

moc_transceiveradjustments.cpp: transceiveradjustments.h \
		rigidentities.h \
		freqmemory.h \
		wfviewtypes.h \
		packettypes.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/bob/work/wfview--20240227--12-24-00/wfview/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/bob/work/wfview--20240227--12-24-00/wfview -I/home/bob/work/wfview--20240227--12-24-00/wfview/resampler -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGamepad -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include transceiveradjustments.h -o moc_transceiveradjustments.cpp

moc_selectradio.cpp: selectradio.h \
		packettypes.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/bob/work/wfview--20240227--12-24-00/wfview/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/bob/work/wfview--20240227--12-24-00/wfview -I/home/bob/work/wfview--20240227--12-24-00/wfview/resampler -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGamepad -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include selectradio.h -o moc_selectradio.cpp

moc_tcpserver.cpp: tcpserver.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/bob/work/wfview--20240227--12-24-00/wfview/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/bob/work/wfview--20240227--12-24-00/wfview -I/home/bob/work/wfview--20240227--12-24-00/wfview/resampler -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGamepad -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include tcpserver.h -o moc_tcpserver.cpp

moc_cluster.cpp: cluster.h \
		database.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/bob/work/wfview--20240227--12-24-00/wfview/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/bob/work/wfview--20240227--12-24-00/wfview -I/home/bob/work/wfview--20240227--12-24-00/wfview/resampler -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGamepad -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include cluster.h -o moc_cluster.cpp

moc_aboutbox.cpp: aboutbox.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/bob/work/wfview--20240227--12-24-00/wfview/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/bob/work/wfview--20240227--12-24-00/wfview -I/home/bob/work/wfview--20240227--12-24-00/wfview/resampler -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGamepad -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include aboutbox.h -o moc_aboutbox.cpp

moc_audiodevices.cpp: audiodevices.h \
		wfviewtypes.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/bob/work/wfview--20240227--12-24-00/wfview/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/bob/work/wfview--20240227--12-24-00/wfview -I/home/bob/work/wfview--20240227--12-24-00/wfview/resampler -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGamepad -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include audiodevices.h -o moc_audiodevices.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_wfmain.h ui_calibrationwindow.h ui_cwsender.h ui_loggingwindow.h ui_satellitesetup.h ui_selectradio.h ui_repeatersetup.h ui_transceiveradjustments.h ui_controllersetup.h ui_aboutbox.h
compiler_uic_clean:
	-$(DEL_FILE) ui_wfmain.h ui_calibrationwindow.h ui_cwsender.h ui_loggingwindow.h ui_satellitesetup.h ui_selectradio.h ui_repeatersetup.h ui_transceiveradjustments.h ui_controllersetup.h ui_aboutbox.h
ui_wfmain.h: wfmain.ui \
		/usr/lib/qt5/bin/uic \
		meter.h \
		qledlabel.h \
		rigcommander.h \
		wfviewtypes.h \
		commhandler.h \
		pttyhandler.h \
		rigidentities.h \
		freqmemory.h \
		packettypes.h \
		udphandler.h \
		audiohandler.h \
		audiotaper.h \
		audioconverter.h \
		resampler/speex_resampler.h \
		udpbase.h \
		udpcivdata.h \
		udpaudio.h \
		pahandler.h \
		rthandler.h \
		repeaterattributes.h \
		tcpserver.h \
		rigstate.h
	/usr/lib/qt5/bin/uic wfmain.ui -o ui_wfmain.h

ui_calibrationwindow.h: calibrationwindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic calibrationwindow.ui -o ui_calibrationwindow.h

ui_cwsender.h: cwsender.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic cwsender.ui -o ui_cwsender.h

ui_loggingwindow.h: loggingwindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic loggingwindow.ui -o ui_loggingwindow.h

ui_satellitesetup.h: satellitesetup.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic satellitesetup.ui -o ui_satellitesetup.h

ui_selectradio.h: selectradio.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic selectradio.ui -o ui_selectradio.h

ui_repeatersetup.h: repeatersetup.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic repeatersetup.ui -o ui_repeatersetup.h

ui_transceiveradjustments.h: transceiveradjustments.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic transceiveradjustments.ui -o ui_transceiveradjustments.h

ui_controllersetup.h: controllersetup.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic controllersetup.ui -o ui_controllersetup.h

ui_aboutbox.h: aboutbox.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic aboutbox.ui -o ui_aboutbox.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp keyboard.h \
		wfmain.h \
		servermain.h \
		logcategories.h \
		commhandler.h \
		wfviewtypes.h \
		rigcommander.h \
		pttyhandler.h \
		rigidentities.h \
		freqmemory.h \
		packettypes.h \
		udphandler.h \
		audiohandler.h \
		audiotaper.h \
		audioconverter.h \
		resampler/speex_resampler.h \
		udpbase.h \
		udpcivdata.h \
		udpaudio.h \
		pahandler.h \
		rthandler.h \
		repeaterattributes.h \
		tcpserver.h \
		rigstate.h \
		audiodevices.h \
		udpserver.h \
		rigctld.h \
		prefs.h \
		calibrationwindow.h \
		repeatersetup.h \
		satellitesetup.h \
		transceiveradjustments.h \
		cwsender.h \
		cwsidetone.h \
		qledlabel.h \
		aboutbox.h \
		selectradio.h \
		colorprefs.h \
		loggingwindow.h \
		cluster.h \
		database.h \
		sidebandchooser.h \
		usbcontroller.h \
		controllersetup.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

cwsender.o: cwsender.cpp cwsender.h \
		cwsidetone.h \
		wfviewtypes.h \
		ui_cwsender.h \
		logcategories.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cwsender.o cwsender.cpp

cwsidetone.o: cwsidetone.cpp cwsidetone.h \
		logcategories.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cwsidetone.o cwsidetone.cpp

loggingwindow.o: loggingwindow.cpp loggingwindow.h \
		logcategories.h \
		ui_loggingwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o loggingwindow.o loggingwindow.cpp

wfmain.o: wfmain.cpp wfmain.h \
		servermain.h \
		logcategories.h \
		commhandler.h \
		wfviewtypes.h \
		rigcommander.h \
		pttyhandler.h \
		rigidentities.h \
		freqmemory.h \
		packettypes.h \
		udphandler.h \
		audiohandler.h \
		audiotaper.h \
		audioconverter.h \
		resampler/speex_resampler.h \
		udpbase.h \
		udpcivdata.h \
		udpaudio.h \
		pahandler.h \
		rthandler.h \
		repeaterattributes.h \
		tcpserver.h \
		rigstate.h \
		audiodevices.h \
		udpserver.h \
		rigctld.h \
		prefs.h \
		calibrationwindow.h \
		repeatersetup.h \
		satellitesetup.h \
		transceiveradjustments.h \
		cwsender.h \
		cwsidetone.h \
		qledlabel.h \
		aboutbox.h \
		selectradio.h \
		colorprefs.h \
		loggingwindow.h \
		cluster.h \
		database.h \
		sidebandchooser.h \
		usbcontroller.h \
		controllersetup.h \
		ui_wfmain.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wfmain.o wfmain.cpp

commhandler.o: commhandler.cpp commhandler.h \
		wfviewtypes.h \
		logcategories.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o commhandler.o commhandler.cpp

rigcommander.o: rigcommander.cpp rigcommander.h \
		wfviewtypes.h \
		commhandler.h \
		pttyhandler.h \
		rigidentities.h \
		freqmemory.h \
		packettypes.h \
		udphandler.h \
		audiohandler.h \
		audiotaper.h \
		audioconverter.h \
		resampler/speex_resampler.h \
		udpbase.h \
		udpcivdata.h \
		udpaudio.h \
		pahandler.h \
		rthandler.h \
		repeaterattributes.h \
		tcpserver.h \
		rigstate.h \
		logcategories.h \
		printhex.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rigcommander.o rigcommander.cpp

freqmemory.o: freqmemory.cpp freqmemory.h \
		wfviewtypes.h \
		logcategories.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o freqmemory.o freqmemory.cpp

rigidentities.o: rigidentities.cpp rigidentities.h \
		freqmemory.h \
		wfviewtypes.h \
		packettypes.h \
		logcategories.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rigidentities.o rigidentities.cpp

udpbase.o: udpbase.cpp udpbase.h \
		packettypes.h \
		logcategories.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o udpbase.o udpbase.cpp

udphandler.o: udphandler.cpp udphandler.h \
		packettypes.h \
		audiohandler.h \
		audiotaper.h \
		audioconverter.h \
		wfviewtypes.h \
		resampler/speex_resampler.h \
		udpbase.h \
		udpcivdata.h \
		udpaudio.h \
		pahandler.h \
		rthandler.h \
		logcategories.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o udphandler.o udphandler.cpp

udpcivdata.o: udpcivdata.cpp udpcivdata.h \
		packettypes.h \
		udpbase.h \
		logcategories.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o udpcivdata.o udpcivdata.cpp

udpaudio.o: udpaudio.cpp udpaudio.h \
		packettypes.h \
		udpbase.h \
		audiohandler.h \
		audiotaper.h \
		audioconverter.h \
		wfviewtypes.h \
		resampler/speex_resampler.h \
		pahandler.h \
		rthandler.h \
		logcategories.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o udpaudio.o udpaudio.cpp

logcategories.o: logcategories.cpp logcategories.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o logcategories.o logcategories.cpp

pahandler.o: pahandler.cpp pahandler.h \
		packettypes.h \
		audiotaper.h \
		audiohandler.h \
		audioconverter.h \
		wfviewtypes.h \
		resampler/speex_resampler.h \
		logcategories.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pahandler.o pahandler.cpp

rthandler.o: rthandler.cpp rthandler.h \
		packettypes.h \
		audiotaper.h \
		audiohandler.h \
		audioconverter.h \
		wfviewtypes.h \
		resampler/speex_resampler.h \
		logcategories.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rthandler.o rthandler.cpp

audiohandler.o: audiohandler.cpp audiohandler.h \
		packettypes.h \
		audiotaper.h \
		audioconverter.h \
		wfviewtypes.h \
		resampler/speex_resampler.h \
		logcategories.h \
		ulaw.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o audiohandler.o audiohandler.cpp

audioconverter.o: audioconverter.cpp audioconverter.h \
		wfviewtypes.h \
		resampler/speex_resampler.h \
		packettypes.h \
		logcategories.h \
		ulaw.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o audioconverter.o audioconverter.cpp

calibrationwindow.o: calibrationwindow.cpp calibrationwindow.h \
		ui_calibrationwindow.h \
		logcategories.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o calibrationwindow.o calibrationwindow.cpp

satellitesetup.o: satellitesetup.cpp satellitesetup.h \
		ui_satellitesetup.h \
		logcategories.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o satellitesetup.o satellitesetup.cpp

udpserver.o: udpserver.cpp udpserver.h \
		packettypes.h \
		rigidentities.h \
		freqmemory.h \
		wfviewtypes.h \
		udphandler.h \
		audiohandler.h \
		audiotaper.h \
		audioconverter.h \
		resampler/speex_resampler.h \
		udpbase.h \
		udpcivdata.h \
		udpaudio.h \
		pahandler.h \
		rthandler.h \
		rigcommander.h \
		commhandler.h \
		pttyhandler.h \
		repeaterattributes.h \
		tcpserver.h \
		rigstate.h \
		logcategories.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o udpserver.o udpserver.cpp

meter.o: meter.cpp meter.h \
		rigcommander.h \
		wfviewtypes.h \
		commhandler.h \
		pttyhandler.h \
		rigidentities.h \
		freqmemory.h \
		packettypes.h \
		udphandler.h \
		audiohandler.h \
		audiotaper.h \
		audioconverter.h \
		resampler/speex_resampler.h \
		udpbase.h \
		udpcivdata.h \
		udpaudio.h \
		pahandler.h \
		rthandler.h \
		repeaterattributes.h \
		tcpserver.h \
		rigstate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o meter.o meter.cpp

qledlabel.o: qledlabel.cpp qledlabel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qledlabel.o qledlabel.cpp

pttyhandler.o: pttyhandler.cpp pttyhandler.h \
		rigidentities.h \
		freqmemory.h \
		wfviewtypes.h \
		packettypes.h \
		logcategories.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pttyhandler.o pttyhandler.cpp

resample.o: resampler/resample.c resampler/speex_resampler.h \
		resampler/arch.h \
		resampler/resample_sse.h \
		resampler/resample_neon.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o resample.o resampler/resample.c

repeatersetup.o: repeatersetup.cpp repeatersetup.h \
		repeaterattributes.h \
		rigidentities.h \
		freqmemory.h \
		wfviewtypes.h \
		packettypes.h \
		ui_repeatersetup.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o repeatersetup.o repeatersetup.cpp

rigctld.o: rigctld.cpp rigctld.h \
		rigcommander.h \
		wfviewtypes.h \
		commhandler.h \
		pttyhandler.h \
		rigidentities.h \
		freqmemory.h \
		packettypes.h \
		udphandler.h \
		audiohandler.h \
		audiotaper.h \
		audioconverter.h \
		resampler/speex_resampler.h \
		udpbase.h \
		udpcivdata.h \
		udpaudio.h \
		pahandler.h \
		rthandler.h \
		repeaterattributes.h \
		tcpserver.h \
		rigstate.h \
		logcategories.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rigctld.o rigctld.cpp

usbcontroller.o: usbcontroller.cpp usbcontroller.h \
		rigidentities.h \
		freqmemory.h \
		wfviewtypes.h \
		packettypes.h \
		logcategories.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o usbcontroller.o usbcontroller.cpp

controllersetup.o: controllersetup.cpp controllersetup.h \
		usbcontroller.h \
		rigidentities.h \
		freqmemory.h \
		wfviewtypes.h \
		packettypes.h \
		ui_controllersetup.h \
		logcategories.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o controllersetup.o controllersetup.cpp

transceiveradjustments.o: transceiveradjustments.cpp transceiveradjustments.h \
		rigidentities.h \
		freqmemory.h \
		wfviewtypes.h \
		packettypes.h \
		ui_transceiveradjustments.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o transceiveradjustments.o transceiveradjustments.cpp

selectradio.o: selectradio.cpp logcategories.h \
		selectradio.h \
		packettypes.h \
		ui_selectradio.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o selectradio.o selectradio.cpp

tcpserver.o: tcpserver.cpp tcpserver.h \
		logcategories.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tcpserver.o tcpserver.cpp

cluster.o: cluster.cpp cluster.h \
		database.h \
		logcategories.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cluster.o cluster.cpp

database.o: database.cpp database.h \
		logcategories.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o database.o database.cpp

aboutbox.o: aboutbox.cpp aboutbox.h \
		ui_aboutbox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o aboutbox.o aboutbox.cpp

audiodevices.o: audiodevices.cpp audiodevices.h \
		wfviewtypes.h \
		logcategories.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o audiodevices.o audiodevices.cpp

qrc_style.o: qrc_style.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_style.o qrc_style.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_wfmain.o: moc_wfmain.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_wfmain.o moc_wfmain.cpp

moc_commhandler.o: moc_commhandler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_commhandler.o moc_commhandler.cpp

moc_cwsender.o: moc_cwsender.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cwsender.o moc_cwsender.cpp

moc_cwsidetone.o: moc_cwsidetone.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cwsidetone.o moc_cwsidetone.cpp

moc_loggingwindow.o: moc_loggingwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_loggingwindow.o moc_loggingwindow.cpp

moc_rigcommander.o: moc_rigcommander.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rigcommander.o moc_rigcommander.cpp

moc_udphandler.o: moc_udphandler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_udphandler.o moc_udphandler.cpp

moc_udpcivdata.o: moc_udpcivdata.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_udpcivdata.o moc_udpcivdata.cpp

moc_udpaudio.o: moc_udpaudio.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_udpaudio.o moc_udpaudio.cpp

moc_pahandler.o: moc_pahandler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pahandler.o moc_pahandler.cpp

moc_rthandler.o: moc_rthandler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rthandler.o moc_rthandler.cpp

moc_audiohandler.o: moc_audiohandler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_audiohandler.o moc_audiohandler.cpp

moc_audioconverter.o: moc_audioconverter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_audioconverter.o moc_audioconverter.cpp

moc_calibrationwindow.o: moc_calibrationwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_calibrationwindow.o moc_calibrationwindow.cpp

moc_satellitesetup.o: moc_satellitesetup.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_satellitesetup.o moc_satellitesetup.cpp

moc_udpserver.o: moc_udpserver.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_udpserver.o moc_udpserver.cpp

moc_meter.o: moc_meter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_meter.o moc_meter.cpp

moc_qledlabel.o: moc_qledlabel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qledlabel.o moc_qledlabel.cpp

moc_pttyhandler.o: moc_pttyhandler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pttyhandler.o moc_pttyhandler.cpp

moc_repeatersetup.o: moc_repeatersetup.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_repeatersetup.o moc_repeatersetup.cpp

moc_rigctld.o: moc_rigctld.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rigctld.o moc_rigctld.cpp

moc_usbcontroller.o: moc_usbcontroller.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_usbcontroller.o moc_usbcontroller.cpp

moc_controllersetup.o: moc_controllersetup.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_controllersetup.o moc_controllersetup.cpp

moc_transceiveradjustments.o: moc_transceiveradjustments.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_transceiveradjustments.o moc_transceiveradjustments.cpp

moc_selectradio.o: moc_selectradio.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_selectradio.o moc_selectradio.cpp

moc_tcpserver.o: moc_tcpserver.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tcpserver.o moc_tcpserver.cpp

moc_cluster.o: moc_cluster.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cluster.o moc_cluster.cpp

moc_aboutbox.o: moc_aboutbox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_aboutbox.o moc_aboutbox.cpp

moc_audiodevices.o: moc_audiodevices.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_audiodevices.o moc_audiodevices.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/usr/local/bin || mkdir -p $(INSTALL_ROOT)/usr/local/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/usr/local/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/usr/local/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/usr/local/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/local/bin/ 


install_applications: first FORCE
	@test -d $(INSTALL_ROOT)/usr/local/share/applications || mkdir -p $(INSTALL_ROOT)/usr/local/share/applications
	$(QINSTALL) /home/bob/work/wfview--20240227--12-24-00/wfview/resources/wfview.desktop $(INSTALL_ROOT)/usr/local/share/applications/wfview.desktop

uninstall_applications: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/applications/wfview.desktop
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/local/share/applications/ 


install_icons: first FORCE
	@test -d $(INSTALL_ROOT)/usr/local/share/icons/hicolor/256x256/apps || mkdir -p $(INSTALL_ROOT)/usr/local/share/icons/hicolor/256x256/apps
	$(QINSTALL) /home/bob/work/wfview--20240227--12-24-00/wfview/resources/unix_icons/wfview.png $(INSTALL_ROOT)/usr/local/share/icons/hicolor/256x256/apps/wfview.png

uninstall_icons: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/icons/hicolor/256x256/apps/wfview.png
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/local/share/icons/hicolor/256x256/apps/ 


install_metainfo: first FORCE
	@test -d $(INSTALL_ROOT)/usr/local/share/metainfo || mkdir -p $(INSTALL_ROOT)/usr/local/share/metainfo
	$(QINSTALL) /home/bob/work/wfview--20240227--12-24-00/wfview/resources/org.wfview.wfview.metainfo.xml $(INSTALL_ROOT)/usr/local/share/metainfo/org.wfview.wfview.metainfo.xml

uninstall_metainfo: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/metainfo/org.wfview.wfview.metainfo.xml
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/local/share/metainfo/ 


install_stylesheets: first FORCE
	@test -d $(INSTALL_ROOT)/usr/local/share/wfview || mkdir -p $(INSTALL_ROOT)/usr/local/share/wfview
	$(QINSTALL) /home/bob/work/wfview--20240227--12-24-00/wfview/qdarkstyle $(INSTALL_ROOT)/usr/local/share/wfview/qdarkstyle

uninstall_stylesheets: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/wfview/qdarkstyle
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/local/share/wfview/ 


install: install_target install_applications install_icons install_metainfo install_stylesheets  FORCE

uninstall: uninstall_target uninstall_applications uninstall_icons uninstall_metainfo uninstall_stylesheets  FORCE

FORCE:

